### PR TITLE
[WIP] Add support for SMBv1

### PR DESCRIPTION
**Pull request by sdaubert**
aims at partly fixing #74

### CODE REVIEW

**Comment by picatz** [comment]
Awesome! 🤘 ✨

**Comment by picatz** [comment]
@sdaubert Would it be possible/advisable to extract the NetBIOS header type from this PR?

Also, and I don't meant to put any pressure on you (you're the best!), when do you think this feature might be available? 

If there's something I can do, just let me know and I'll try my best. 👏

**Comment by sdaubert** [comment]
Looking on SMB specification make my motivation go down. This is a very complex protocol, and work on it only one hour a day is not enough. Perhaps I will work on it again this summer.

**Comment by picatz** [comment]
@sdaubert I can definitely understand the motivation problem when looking at basically any specification. It's something I struggle with too. ❤️

Even if you don't finish this feature, I always appreciate the work you do. 🙏

**Comment by sdaubert** [comment]
Closed. See https://github.com/sdaubert/packetgen-plugin-smb.

**Pull request closed without merging**
