### PR TITLE
Some performance improvements 

### PR DESCRIPTION
**Pull request by picatz**
Spent a little bit of time using the [fasterer](https://github.com/DamirSvrtan/fasterer) gem to find areas where packetgen could improve performance.

### CODE REVIEW

**Comment by sdaubert** [comment]
Manually merged in c9a8101d7 (rebase 4 last commits in one)

**Comment by sdaubert** [comment]
Thanks to help improving packetgen :thumbsup:

**Comment by picatz** [comment]
@sdaubert Thank _you_ for making it in the first place, I always love using it! 👏 ❤️

**Comment by KINGSABRI** [comment]
as always @picatz is awesome!

**Pull request closed without merging**
